# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'entrance.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1182, 717)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.Frame = QtWidgets.QFrame(self.centralwidget)
        self.Frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Frame.setStyleSheet("background: #2A2A44;")
        self.Frame.setObjectName("Frame")
        self.libraryLayout = QtWidgets.QVBoxLayout(self.Frame)
        self.libraryLayout.setObjectName("libraryLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.libraryLayout.addItem(spacerItem)
        self.emailHorizontalLayout = QtWidgets.QHBoxLayout()
        self.emailHorizontalLayout.setObjectName("emailHorizontalLayout")
        self.emailLineEdit = QtWidgets.QLineEdit(self.Frame)
        self.emailLineEdit.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.emailLineEdit.setFont(font)
        self.emailLineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.emailLineEdit.setStyleSheet("background: #A2A2E8;\n"
"border-radius: 10px;\n"
"")
        self.emailLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.emailHorizontalLayout.addWidget(self.emailLineEdit)
        self.libraryLayout.addLayout(self.emailHorizontalLayout)
        self.passwordHorizontalLayout = QtWidgets.QHBoxLayout()
        self.passwordHorizontalLayout.setObjectName("passwordHorizontalLayout")
        self.passwordLineEdit = QtWidgets.QLineEdit(self.Frame)
        self.passwordLineEdit.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setStyleSheet("background: #A2A2E8;\n"
"border-radius: 10px;\n"
"margin-top: 40px;")
        self.passwordLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.passwordHorizontalLayout.addWidget(self.passwordLineEdit)
        self.libraryLayout.addLayout(self.passwordHorizontalLayout)
        self.buttonHorizontalLayout = QtWidgets.QHBoxLayout()
        self.buttonHorizontalLayout.setObjectName("buttonHorizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonHorizontalLayout.addItem(spacerItem1)
        self.entrancePushButton = QtWidgets.QPushButton(self.Frame)
        self.entrancePushButton.setMinimumSize(QtCore.QSize(250, 0))
        self.entrancePushButton.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.entrancePushButton.setFont(font)
        self.entrancePushButton.setStyleSheet("background: #A2A2E8;\n"
"border-radius: 10px;\n"
"margin-top: 40px;\n"
"margin-right:10px;")
        self.entrancePushButton.setObjectName("entrancePushButton")
        self.buttonHorizontalLayout.addWidget(self.entrancePushButton)
        self.registrationPushButton = QtWidgets.QPushButton(self.Frame)
        self.registrationPushButton.setMinimumSize(QtCore.QSize(250, 0))
        self.registrationPushButton.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.registrationPushButton.setFont(font)
        self.registrationPushButton.setStyleSheet("background: #A2A2E8;\n"
"border-radius: 10px;\n"
"margin-top:40px;\n"
"margin-left:10px;")
        self.registrationPushButton.setObjectName("registrationPushButton")
        self.buttonHorizontalLayout.addWidget(self.registrationPushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonHorizontalLayout.addItem(spacerItem2)
        self.libraryLayout.addLayout(self.buttonHorizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.libraryLayout.addItem(spacerItem3)
        self.gridLayout.addWidget(self.Frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.emailLineEdit.setPlaceholderText(_translate("MainWindow", "Email"))
        self.passwordLineEdit.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.entrancePushButton.setText(_translate("MainWindow", "Вход"))
        self.registrationPushButton.setText(_translate("MainWindow", "Регистрация"))



#ОТСЮДА И ДО КОНЦА ФАЙЛА

class Enter(QtWidgets.QMainWindow): #?????
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        self.pushButton.clicked.connect(self.onClicked)                        # +++

    def checkEmail(self):
        CHECK = 0
        email = self.emailLineEdit.text()
        COUNT = 0
        PLACE = 0
        Count_for_letter_1, Count_for_letter_2 = 0, 0
        for i in range(0, len(email)):
            if email[i] == '@':
                COUNT += 1
                PLACE = i
        ERROR = 0
        if COUNT == 1:
            for i in range(0, len(email)):
                if i < PLACE:
                    Count_for_letter_1 += 1
                    if not ('a' <= email[i] <= 'z'):
                        if (email[i] == '.' or email[i] == '-') and (
                                email[i] == email[i + 1] or i == 0 or i == (PLACE - 1)):
                            ERROR += 1
                if i > PLACE:
                    Count_for_letter_2 += 1
                    if not ('a' <= email[i] <= 'z'):
                        if (email[i] == '.' or email[i] == '-') and (
                                email[i] == email[i + 1] or i == PLACE or i == (PLACE + 1)):
                            ERROR += 1
        if Count_for_letter_1 != 0 and Count_for_letter_2 != 0 and ERROR == 0:
            CHECK = 1

    def onClicked(self, CHECK):
        if CHECK == 1:
            msg = QtWidgets.QMessageBox.information(self, 'Welcome', 'Добро пожаловать!')
        else:
            msg = QtWidgets.QMessageBox.information(self, 'Error', 'Неправильный пароль')

